### ISSUE TITLE
Endorse MDN instead of Web Platform Docs

### ISSUE THREAD

**Issue by AldoMX** [paulirish/w3fools#71]
Hi there,

The WPD website has the following notice at the top of every webpage:

> **Notice:** The WebPlatform project has been **discontinued** when the [Stewards partnership](http://blog.webplatform.org/2012/10/one-small-step/) agreement ended in *September 2015*. This site has been frozen, and the assets we have created will remain.

I believe the most sensible choice at 2016 would be to endorse MDN.

**Comment by Garbee** [comment]
We have done that for a long time. However, we should amend the statement
to de-emphasize WPD as a current resource due to no further editing.

**Comment by paulirish** [comment]
i've removed the references to WPD
